#pragma once

#define RETWIS_NUM_TRANSACTIONS_PER_CLIENT 100000

#define RETWIS_INIT_USERS 673000000

#define RETWIS_ADD_USER_PROPORTION 0.05
#define RETWIS_POST_PROPORTION     0.3
#define RETWIS_FOLLOW_PROPORTION   0.15
#define RETWIS_TIMELINE_PROPORTION 0.5

#define RETWIS_MAX_TXN_RETRIES      0
#define RETWIS_TXN_RETRY_PENALTY_NS 0